#!/usr/bin/env python
import os
import logging
from opt.utils import (get_function,ScriptError,setup_run)
from opt.utils.script_utils.parsing import build_parser

logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))

def main(args):
    # setup
    mode_args = setup_run(args)
    
    #get function
    func=get_function(mode_args)
    
    #get parameter
    
    
    
    
    
if __name__ == "__main__":
    parser = build_parser()
    args = parser.parse_args()

    if args.mode == "from_json":
        args = opt.utils.read_from_json(args.json_path)

    import argparse

    main(args)
